version: "3.1"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8888:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"
  

  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    restart: on-failure
    command: --lower_case_table_names=2

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./backend/static:/usr/share/nginx/doc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

  redis:
    image: redis:alpine


  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info"

