# Generated by Django 5.1.1 on 2024-09-10 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='price',
        ),
        migrations.CreateModel(
            name='CarPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('initial_currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], max_length=3)),
                ('current_USD', models.DecimalField(decimal_places=5, max_digits=10)),
                ('current_EUR', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price_in_USD', models.DecimalField(decimal_places=5, max_digits=20)),
                ('price_in_EUR', models.DecimalField(decimal_places=5, max_digits=20)),
                ('price_in_UAH', models.DecimalField(decimal_places=5, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='cars.carmodel')),
            ],
        ),
    ]
