# Generated by Django 5.1.1 on 2024-09-10 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carmodel_price_carpricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], max_length=3)),
                ('buy_price', models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='carpricemodel',
            name='current_EUR',
        ),
        migrations.RemoveField(
            model_name='carpricemodel',
            name='current_USD',
        ),
        migrations.RemoveField(
            model_name='carpricemodel',
            name='last_updated',
        ),
    ]
