# Generated by Django 5.1.1 on 2024-09-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_currencymodel_remove_carpricemodel_current_eur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpricemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='currencymodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='carpricemodel',
            table='car_price',
        ),
        migrations.AlterModelTable(
            name='currencymodel',
            table='currency',
        ),
    ]
