# Generated by Django 5.1.1 on 2024-09-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carpricemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='currency',
        ),
    ]
