# Generated by Django 5.1.1 on 2024-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_viewstatisticsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], max_length=3, unique=True),
        ),
    ]
