# Generated by Django 5.1.1 on 2024-09-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_currencymodel_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymodel',
            name='last_update',
        ),
    ]
