# Generated by Django 5.1.1 on 2024-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_currencymodel_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymodel',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
