# Generated by Django 5.1 on 2024-09-08 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'db_table': 'car_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], max_length=3)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)])),
                ('body_type', models.CharField(choices=[('HatchBack', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep'), ('Minivan', 'Minivan'), ('LiftBack', 'Liftback'), ('MicroVan', 'Microvan'), ('PickUp', 'Pickup'), ('Roadster', 'Roadster'), ('Cabriolet', 'Cabriolet'), ('Limousine', 'Limousine'), ('FastBack', 'Fastback')], max_length=9)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CarModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'db_table': 'car_models',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='CarProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('region', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_used', models.BooleanField(default=False)),
                ('engine_type', models.CharField(choices=[('PetrolEngine', 'Petrolengine'), ('DieselEngine', 'Dieselengine'), ('ElectricMotor', 'Electricmotor')], max_length=20)),
                ('transmission_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'car_profile',
                'ordering': ['id'],
            },
        ),
    ]
