# Generated by Django 5.1 on 2024-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carprofilemodel',
            name='is_used',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
