# Generated by Django 5.1 on 2024-09-09 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_carprofilemodel_is_used_carmodel_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='edit_attempts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carprofilemodel',
            name='color',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carprofilemodel',
            name='owner_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='carprofilemodel',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
