# Generated by Django 5.1 on 2024-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_edit_attempts_carmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
