# Generated by Django 5.1 on 2024-09-09 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodelmodel',
            options={'ordering': ['-brand']},
        ),
        migrations.AddField(
            model_name='carprofilemodel',
            name='engine_volume',
            field=models.FloatField(default=5.6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carprofilemodel',
            name='region',
            field=models.CharField(choices=[('Vinnytsia', 'Vinnytsia'), ('Volyn', 'Volyn'), ('Dnipropetrovsk', 'Dnipropetrovsk'), ('Donetsk', 'Donetsk'), ('Zhytomyr', 'Zhytomyr'), ('Zakarpattia', 'Zakarpattia'), ('Zaporizhzhia', 'Zaporizhzhia'), ('Ivano-Frankivsk', 'Ivanofrankivsk'), ('Kyiv', 'Kyiv'), ('Kirovohrad', 'Kirovohrad'), ('Luhansk', 'Luhansk'), ('Lviv', 'Lviv'), ('Mykolaiv', 'Mykolaiv'), ('Odesa', 'Odesa'), ('Poltava', 'Poltava'), ('Rivne', 'Rivne'), ('Sumy', 'Sumy'), ('Ternopil', 'Ternopil'), ('Kharkiv', 'Kharkiv'), ('Kherson', 'Kherson'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Krym', 'Krym'), ('Cherkasy', 'Cherkasy'), ('Chernivtsi', 'Chernivtsi'), ('Chernihiv', 'Chernihiv')], max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
