# Generated by Django 5.1 on 2024-09-09 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default='+380936789435', max_length=13, validators=[django.core.validators.RegexValidator('^\\+380(39|50|63|66|67|68|73|91|92|93|94|95|96|97|98|99)\\d{7}$', ['Phone number must start with +380', 'Phone number must contain a valid operator code (39, 50, 63, 66, 67, 68, 73, 91, 92, 93, 94, 95, 96, 97, 98, 99)', 'Phone number must contain exactly 7 digits after the operator code'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{1,19}$', 'First letter uppercase, min 2, max 20')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])(\\S){8,18}$', ['Password must contain at least 1 number (1-9)', 'Password must contain at least 1 uppercase letter', 'Password must contain at least 1 lowercase letter', 'Password must contain at least 1 special character', 'Password must contain min 8 max 16 characters without spaces'])], verbose_name='password'),
        ),
    ]
