from django.db import models


class RegionChoices(models.TextChoices):
    Vinnytsia = "Vinnytsia"
    Volyn = "Volyn"
    Dnipropetrovsk = "Dnipropetrovsk"
    Donetsk = "Donetsk"
    Zhytomyr = "Zhytomyr"
    Zakarpattia = "Zakarpattia"
    Zaporizhzhia = "Zaporizhzhia"
    IvanoFrankivsk = "Ivano-Frankivsk"
    Kyiv = "Kyiv"
    Kirovohrad = "Kirovohrad"
    Luhansk = "Luhansk"
    Lviv = "Lviv"
    Mykolaiv = "Mykolaiv"
    Odesa = "Odesa"
    Poltava = "Poltava"
    Rivne = "Rivne"
    Sumy = "Sumy"
    Ternopil = "Ternopil"
    Kharkiv = "Kharkiv"
    Kherson = "Kherson"
    Khmelnytskyi = "Khmelnytskyi"
    Krym = "Krym"
    Cherkasy = "Cherkasy"
    Chernivtsi = "Chernivtsi"
    Chernihiv = "Chernihiv"
